---
- name: Set timezone to 'Central Standard Time' (GMT-06:00)
  community.windows.win_timezone:
    timezone: Central Standard Time

- name: 'Sets NTP as time protocol'
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: Type
    data: '{{ ntp.time_type }}'
    type: string

- name: 'Sets NTP Server'
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: NtpServer
    data: "{{ ntp.server | join(',' + ntp.flag + ' ') }}"
    type: string

- name: Sets NTP Client Settings
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\W32time\TimeProviders\NtpClient
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  with_items:
    - name: CrossSiteSyncFlags
      data: '{{ ntp.crosssitesyncflags }}'
    - name: ResolvePeerBackoffMinutes
      data: '{{ ntp.resolvepeerbackoffminutes }}'
    - name: ResolvePeerBackoffMaxTimes
      data: '{{ ntp.resolvepeerbackoffmaxtimes }}'
    - name: SpecialPollInterval
      data: '{{ ntp.specialpollinterval }}'
    - name: EventLogFlags
      data: '{{ ntp.eventlogflags }}'

- name: Make sure ntp service is started
  win_service:
    name: "{{ ntp.service_name }}"
    start_mode: auto
    state: started

- name: update ntp config
  win_shell: w32tm /config /update

- name: Restart ntp service
  win_service:
    name: "{{ ntp.service_name }}"
    state: restarted
