---
- name: Windows | Set timezone to 'Central Standard Time' (GMT-06:00)
  community.windows.win_timezone:
    timezone: "{{ ntp.windows.timezone }}"

- name: Windows | Set NTP as time protocol
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: Type
    data: '{{ ntp.windows.time_type }}'
    type: string

- name: Windows | Set NTP Server
  win_regedit:
    path: HKLM:\Software\Policies\Microsoft\W32time\Parameters
    name: NtpServer
    data: "{{ ntp.server | join(',' + ntp.windows.flag + ' ') }}"
    type: string

- name: Windows | Set NTP Client Settings
  win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\W32time\TimeProviders\NtpClient
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    type: dword
  with_items:
    - name: CrossSiteSyncFlags
      data: '{{ ntp.windows.crosssitesyncflags }}'
    - name: ResolvePeerBackoffMinutes
      data: '{{ ntp.windows.resolvepeerbackoffminutes }}'
    - name: ResolvePeerBackoffMaxTimes
      data: '{{ ntp.windows.resolvepeerbackoffmaxtimes }}'
    - name: SpecialPollInterval
      data: '{{ ntp.windows.specialpollinterval }}'
    - name: EventLogFlags
      data: '{{ ntp.windows.eventlogflags }}'

- name: Windows | Start NTP service
  win_service:
    name: "{{ ntp.windows.service_name }}"
    start_mode: auto
    state: started

- name: Windows | Update NTP configuration
  win_shell: w32tm /config /update

- name: Windows | Restart NTP service
  win_service:
    name: "{{ ntp.windows.service_name }}"
    state: restarted

