---
- name: Windows | Copy over Splunk inputs.conf
  ansible.builtin.template:
    src: "{{ splunk_uf.windows.conf.inputs.local_path }}"
    dest: "{{ splunk_uf.windows.conf.inputs.path }}"
    newline_sequence: '\r\n'
  notify:
    - Restart splunk forwarder
