---
- name: Windows | Ensure Splunk UF directory is removed
  ansible.windows.win_file:
    path: "{{ splunk_uf.windows.path }}"
    state: absent

- name: Windows | Install Splunk Universal Forwarder
  ansible.windows.win_package:
    path: "{{ splunk_uf.windows.url }}"
    arguments:
    - AGREETOLICENSE=yes 
    - "RECEIVING_INDEXER={{ splunk_uf.windows.indexer.address }}:{{ splunk_uf.windows.indexer.port }}"
    - /quiet

- name: Windows | Start splunk service
  ansible.windows.win_powershell:
    script: |
      Start-Service -Name (Get-Service | where {$_.Name -like "Splunk*"} ).Name

- name: Windows | Download Splunk UF installer for uninstall purposes
  ansible.windows.win_get_url:
    url: "{{ splunk_uf.windows.url }}"
    dest: "{{ splunk_uf.windows.path }}\\{{ splunk_uf.windows.temp.exe }}"

- name: Windows | Copy over Splunk outputs.conf
  ansible.builtin.template:
    src: "{{ splunk_uf.windows.conf.outputs.local_path }}"
    dest: "{{ splunk_uf.windows.conf.outputs.path }}"
    newline_sequence: '\r\n'

- name: Windows | Copy over Splunk inputs.conf
  ansible.builtin.template:
    src: "{{ splunk_uf.windows.conf.inputs.local_path }}"
    dest: "{{ splunk_uf.windows.conf.inputs.path }}"
    newline_sequence: '\r\n'
  notify:
    - Restart splunk forwarder

- name: Windows | Clear the logs and restart splunk
  include_tasks: win_clear_logs.yml
