---
- name: Windows | Check if Splunk UF service is installed
  win_service:
    name: SplunkForwarder
  register: splunk_uf_service

- name: Windows | Uninstall Splunk Universal Forwarder
  ansible.windows.win_package:
    path: "{{ splunk_uf.windows.path }}\\{{ splunk_uf.windows.temp.exe }}"
    state: absent
  when: splunk_uf_service.exists

- name: Windows | Ensure Splunk UF directory is removed
  ansible.windows.win_file:
    path: "{{ splunk_uf.windows.path }}"
    state: absent
