---
- name:
  win_service:
    name: "{{ velociraptor.service_name }}"
  register: velociraptor_service
  when: ansible_os_family == 'Windows'

- name:
  include_tasks: win_install.yml
  when: ansible_os_family == 'Windows' and not velociraptor_service.exists
