---
- name: Windows | Check if Velociraptor is installed
  win_service:
    name: Velociraptor
  register: velociraptor_service

- name: Windows | Stop velociraptor service
  win_command: "sc.exe stop {{ velociraptor.service_name }}"
  ignore_errors: yes

- name: Windows | Delete velociraptor service
  win_command: "sc.exe delete {{ velociraptor.service_name }}"
  ignore_errors: yes

- name: Windows | Remove Velociraptor directory
  ansible.windows.win_file:
    path: "{{ velociraptor.path }}"
    state: absent
