---
- name: Windows | Delete Velociraptor directory 
  ansible.windows.win_file:
    path: "{{ velociraptor.path }}"
    state: absent

- name: Windows | Create Velociraptor directory 
  ansible.windows.win_file:
    path: "{{ velociraptor.path }}"
    state: directory

- name: Windows | Download Velociraptor executable
  ansible.windows.win_get_url:
    url: "{{ velociraptor.url }}"
    dest: "{{ velociraptor.path }}\\{{ velociraptor.file_name }}"

- name: Windows | Copy local velociraptor config
  ansible.builtin.template:
    src: "{{ velociraptor.local_conf }}"
    dest: "{{ velociraptor.path }}\\{{ velociraptor.conf }}"
    newline_sequence: '\r\n'

- name: Windows | Install velociraptor service
  win_command: "{{ velociraptor.file_name }} --config {{ velociraptor.conf }} service install"
  args:
    chdir: "{{ velociraptor.path }}"
