---
# Possible settings are described under the following link:
# https://getadmx.com/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsTimeService::W32TIME_POLICY_CONFIGURE_NTPCLIENT
ntp:
  windows:
    service_name: W32Time
    time_type: 'NTP'
    crosssitesyncflags: '2'
    resolvepeerbackoffminutes: '15'
    resolvepeerbackoffmaxtimes: '7'
    specialpollinterval: '1024'
    eventlogflags: '0'
    flag: '0x01'
  server:
    - '0.pool.ntp.org'
    - '1.pool.ntp.org'
    - '2.pool.ntp.org'
    - '3.pool.ntp.org'
