---
#- name: Windows | Reboot the host before promotion
#  ansible.windows.win_reboot:
#    connect_timeout: 2
#    reboot_timeout: 60
#    post_reboot_delay: 60
#    test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'

- name: Windows | Promote Secondary Domain Controller
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ domain.name }}"
    domain_admin_user: "{{ domain.admin.user }}@{{ domain.name }}"
    domain_admin_password: "{{ domain.admin.pass }}"
    safe_mode_password: "{{ domain.controller.dsrm_pass }}"
    state: domain_controller
  register: add_dc

- name: Windows | Reboot the Domain Controller
  ansible.windows.win_reboot:
    connect_timeout: 2
    reboot_timeout: 120
    post_reboot_delay: 400
    test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'
  when: add_dc.reboot_required

- name: Windows | Ensure the host is a Domain Controller
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ domain.name }}"
    domain_admin_user: "{{ domain.admin.user }}@{{ domain.name }}"
    domain_admin_password: "{{ domain.admin.pass }}"
    safe_mode_password: "{{ domain.controller.dsrm_pass }}"
    state: domain_controller
  ignore_errors: yes

- name: Ensure the RSAT Tools are installed
  ansible.windows.win_shell: |
      $RSATInstalled=Get-Module -Name ActiveDirectory -ListAvailable

      if (-NOT $RSATInstalled){
          Get-WindowsCapability -Name RSAT* -Online | Add-WindowsCapability -Online
      }