---
- name: Windows | Create a new domain
  ansible.windows.win_domain:
    dns_domain_name: "{{ domain.name }}"
    domain_netbios_name: "{{ domain.controller.netbios }}"
    domain_mode: "{{ domain.mode }}"
    forest_mode: "{{ domain.forest_mode }}"
    safe_mode_password: "{{ domain.controller.dsrm_pass }}"
    create_dns_delegation: "{{ domain.create_dns_delegation }}"
  register: create_domain

- name: Windows | Reboot the Domain Controller
  ansible.windows.win_reboot:
    connect_timeout: 2
    reboot_timeout: 120
    post_reboot_delay: 400
    test_command: 'exit (Get-Service -Name WinRM).Status -ne "Running"'
  when: create_domain.reboot_required

- name: Windows | Ensure the host is a Domain Controller
  ansible.windows.win_domain_controller:
    dns_domain_name: "{{ domain.name }}"
    domain_admin_user: "{{ domain.admin.user }}@{{ domain.name }}"
    domain_admin_password: "{{ domain.admin.pass }}"
    safe_mode_password: "{{ domain.controller.dsrm_pass }}"
    state: domain_controller
