---
- name: Windows | Remove existing GPO temp directry
  ansible.windows.win_file:
    path: "{{ ansible_env.TEMP }}\\{{ gpo.temp.dir }}"
    state: absent

- name: Windows | Create GPO temp directory
  ansible.windows.win_file:
    path: "{{ ansible_env.TEMP }}\\{{ gpo.temp.dir }}"
    state: directory

- name: Windows | Copy over GPO backups
  copy:
    src: "{{ gpo.local.dir }}"
    dest: "{{ ansible_env.TEMP }}\\{{ gpo.temp.dir }}"

- name: Windows | Run GPO import script
  ansible.windows.win_shell: |
      {{ ansible_env.TEMP }}\{{ gpo.temp.dir }}\{{ gpo.script }}
