---
- name: Check if host is a domain controller
  ansible.windows.win_shell: "Get-ADDomainController -Identity {{ domain.controller.ip_address }}"
  ignore_errors: yes
  register: dc_check

- name: Include domain creation tasks
  include_tasks: create_domain.yml
  when: dc_check.failed
