---
- name: Windows | Include domain creation tasks
  include_tasks: create_domain.yml
  when: >
    ansible_os_family == 'Windows' and
    not ansible_windows_domain_member and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname == groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Stand-alone server'

- name: Run Gather Facts
  setup:

- name: Windows | Include domain population tasks
  include_tasks: populate_ad.yml
  when: >
    ansible_os_family == 'Windows' and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname == groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Primary domain controller'

- name: Windows | Include GPO import task
  include_tasks: import_gpo.yml
  when: >
    ansible_os_family == 'Windows' and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname == groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Primary domain controller'

- name: Windows | Include share creation tasks
  include_tasks: create_share.yml
  when: >
    ansible_os_family == 'Windows' and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname == groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Primary domain controller'

- name: Windows | Include add domain controller tasks
  include_tasks: add_domain_controller.yml
  when: >
    ansible_os_family == 'Windows' and
    not ansible_windows_domain_member and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname != groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Stand-alone server'