---
- name: Check if host is a domain controller
  ansible.windows.win_shell: "Get-ADDomainController -Identity {{ domain.controller.ip_address }}"
  ignore_errors: yes
  register: dc_check
  when: ansible_os_family == 'Windows' and inventory_hostname in groups['domain_controller']

- name: Include domain creation tasks
  include_tasks: create_domain.yml
  when: dc_check is defined and dc_check.failed
