---
- name: Windows | Include domain creation tasks
  include_tasks: create_domain.yml
  when: >
    ansible_os_family == 'Windows' and 
    not ansible_windows_domain_member and 
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname == groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Stand-alone server'

- name: Windows | Include add domain controller tasks
  include_tasks: add_domain_controller.yml
  when: >
    ansible_os_family == 'Windows' and 
    not ansible_windows_domain_member and
    inventory_hostname in groups['domain_controller'] and
    inventory_hostname != groups['domain_controller'][0] and
    ansible_windows_domain_role == 'Stand-alone server'
