---

Get-ADDomainController -Identity "{{ }}"





#- name: Domain Controller check
#  ansible.windows.win_domain_controller:
#    dns_domain_name: "{{ dc_domain_name }}"
#    domain_admin_user: "{{ dc_da_username }}@{{ dc_domain_name}}"
#    domain_admin_password: "{{ dc_da_password }}"
#    safe_mode_password: "{{ dc_dsrm_password }}"
#    state: domain_controller
#  ignore_errors: yes
#  register: is_dc
#
#- name: Domain Controller Check Results
#  debug:
#    msg: "Host is already a Domain Controller"
#  when: not is_dc.failed
#
#- name: Include Domain Controller setup tasks
#  include_tasks: setup_domain_controller.yml
#  when: is_dc.failed
#- name: Create new Windows domain in a new forest with specific parameters
#  ansible.windows.win_domain:
#    create_dns_delegation: no
#    database_path: "{{dc_ntds_path}}"
#    dns_domain_name: "{{ dc_domain_name }}"
#    domain_mode: WinThreshold
#    domain_netbios_name: "{{ dc_netbios_name }}"
#    forest_mode: WinThreshold
#    safe_mode_password: "{{ dc_dsrm_password }}"
#    sysvol_path: "{{ dc_sysvol_path }}"
#  register: domain_install
#
#- name: Reboot after DC Promotion
#  ansible.windows.win_reboot:
#    reboot_timeout: 300
#  when: domain_install.reboot_required
#  register: domain_install
#
#- debug:
#    var: res_reboot
#
#- name: Ensure a server is a domain controller
#  ansible.windows.win_domain_controller:
#    dns_domain_name: "{{ dc_domain_name }}"
#    domain_admin_user: "{{ dc_da_username}}@{{ dc_domain_name }}"
#    domain_admin_password: "{{ dc_da_password }}"
#    safe_mode_password: "{{ dc_dsrm_password }}"
#    state: domain_controller
