---
- name: Delete sysmon directory
  ansible.windows.win_file:
    path: "{{ sysmon.path }}"
    state: absent

- name: Download Sysmon 
  ansible.windows.win_get_url:
    url: "{{ sysmon.url }}"
    dest: "{{ sysmon.temp.path }}\\{{ sysmon.temp.file }}"

- name: Unzip sysmon 
  community.windows.win_unzip:
    src: "{{ sysmon.temp.path }}\\{{ sysmon.temp.file }}"
    dest: "{{ sysmon.path }}"
    delete_archive: yes

- name: Copy local Sysmon Config
  ansible.builtin.template:
    src: "{{ sysmon.local.conf }}"
    dest: "{{ sysmon.path }}\\{{ sysmon.conf }}"
    newline_sequence: '\r\n'
  notify: Initial sysmon start
