---
sysmon:
  url: https://download.sysinternals.com/files/Sysmon.zip
  temp:
    path: C:\Windows\Temp
    file: Sysmon.zip
  local:
    conf: roles/sysmon/files/sysmonconfig-export.xml
  exe: Sysmon.exe
  path: C:\Program Files\Sysmon
  conf: sysmonconfig-export.xml

- name: Delete sysmon directory
  ansible.windows.win_file:
    path: "{{ sysmon.path }}"
    state: absent

- name: Download Sysmon 
  ansible.windows.win_get_url:
    url: "{{ sysmon.url }}"
    dest: "{{ sysmon.temp.path }}\\{{ sysmon.temp.file }}"

- name: Unzip sysmon 
  community.windows.win_unzip:
    src: "{{ sysmon.temp.path }}\\{{ s ysmon.temp.file }}"
    dest: "{{ sysmon.path }}"
    delete_archive: yes

- name: Copy local Sysmon Config
  ansible.builtin.template:
    src: "{{ sysmon.local.conf }}"
    dest: "{{ sysmon.local.path }}\\{{ sysmon.conf }}"
    newline_sequence: '\r\n'
  notify: Initial sysmon start
