---
- name: Check for sysmon service
  win_service:
    name: Sysmon
  register: sysmon_service
  when: ansible_os_family == 'Windows'

- name: Run sysmon install tasks
  include_tasks: install.yml
  when: ansible_os_family == 'Windows' and not sysmon_service.exists
