---
- name: Check for sysmon service
  win_service:
    name: Sysmon
  register: sysmon_service
  notify:
    - handler_sysmon

#- debug: var=sysmon_service

#- name: Include Sysmon install tasks
#  include_tasks: sysmon_install.yml
#  when: not sysmon_service.exists
