---
- name: Uninstall sysmon
  win_command: ".\\{{ sysmon.exe }} -u force"
  args:
    chdir: "{{ sysmon.path }}"

- name: Delete directory "{{ sysmon.path }}"
  ansible.windows.win_file:
    path: "{{ sysmon.path }}"
    state: absent
