---
- name: Copy over sysmon configuration
  ansible.windows.win_template:
    src: "{{ sysmon.conf | realpath }}"
    dest: "{{ sysmon.path }}\\{{ sysmon.conf }}"
  register: conf_copy
  notify:
    - Reconfigure sysmon
