---
- name: Check if Splunk UF service is installed
  win_service:
    name: SplunkForwarder
  register: splunk_uf_service

- name: Uninstall Splunk Universal Forwarder
  ansible.windows.win_package:
    path: "{{ splunk_uf.path }}\\{{ splunk_uf.install_file"
    state: absent
  when: splunk_uf_service.exists

- name: Ensure Splunk UF directory is removed
  ansible.windows.win_file:
    path: "{{ splunk_uf.path }}"
    state: absent
