---
- name:  
  set_fact:
    dns_server_1: 127.0.0.1
    dns_server_2: "{{ hostvars[groups['dns'][0]]['ansible_all_ipv4_addresses'][0] | default('8.8.8.8') }}"
  when: inventory_hostname in groups['domain_controller'] 

- name:  
  set_fact:
    dns_server_1: "{{ hostvars[groups['domain_controller'][0]]['ansible_ip_addresses'] | ansible.netcommon.ipv4 | first | default('8.8.8.8') }}"
    dns_server_2: "{{ hostvars[groups['dns'][0]]['ansible_all_ipv4_addresses'][0] | default('8.8.8.8') }}"
  when: inventory_hostname not in groups['domain_controller'] 

- name: Get Current DNS Servers
  ansible.windows.win_shell: |
      $temp_object=(Get-DnsClientServerAddress -InterfaceIndex (Get-NetAdapter).InterfaceIndex -AddressFamily IPv4)

      $return_object = [PSCustomObject]@{
          interface = $temp_object.InterfaceAlias
          addresses = $temp_object.ServerAddresses
      }

      $return_object | ConvertTo-Json
  register: get_dns_script

- name: Process win_shell output
  set_fact:
    dns_client: "{{ get_dns_script.stdout | from_json }}"

- debug: 
    msg: "THEY'RE RIGHT" 
  when: dns_server_1 in dns_client.addresses and dns_server_2 in dns_client.addresses

- debug: 
    msg: "wrong" 
  when: dns_server_1 not in dns_client.addresses or dns_server_2 not in dns_client.addresses
