---
- name: 
  set_fact:
    dns_server_1: "{{ '127.0.0.1' if inventory_hostname in groups['domain_controller'] else hostvars[groups['domain_controller'][0]]['ansible_ssh_host']}}"
    dns_server_2: 8.8.8.8

- name: Update DNS servers addresses
  ansible.windows.win_shell: "Set-DnsClientServerAddress –InterfaceIndex (Get-NetAdapter).InterfaceIndex –ServerAddresses {{ dns_server_1 }}, {{ dns_server_2 }}"
