---
- name: Windows | Notepad++ check
  ansible.windows.win_stat:
    path: "{{ notepadpp.windows.exe }}"
  when: ansible_os_family == 'Windows' 
  register: notepadpp_check

- name: Windows | Include Notepad++ install tasks
  include_tasks: win_install.yml
  when: ansible_os_family == 'Windows' and not notepadpp_check.stat.exists
