---
- name: Windows | Join the domain
  ansible.windows.win_shell: |
      $credentials = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList "{{ domain.admin.user }}@{{ domain.name }}",(ConvertTo-SecureString -String "{{ domain.admin.pass}}" -AsPlainText -Force)

      Add-Computer -DomainName lab.threats.live -Credential $credentials -PassThru -Verbose | ConvertTo-Json
  register: add_computer_results

- name: Windows | Process win_shell output
  set_fact:
    join_results: "{{ add_computer_results.stdout | from_json }}"

- name: Windows | Reboot the Workstation
  ansible.windows.win_reboot:
    connect_timeout: 2
    reboot_timeout: 300
    post_reboot_delay: 150
    test_command: 'exit (Get-Service -Name Netlogon).Status -ne "Running"'
  when: join_results.HasSucceeded == true
