---
- hosts: all
  tasks:
    - block:
        - wait_for_connection:
            sleep: 1
            timeout: 10
      rescue:
        - debug:
            msg: "{{ inventory_hostname }} not connected. End of host."

    - debug:
        msg: "{{ inventory_hostname }} is running"
    - setup:
