- hosts: windows
  tasks:
    - include_role:
        name: sysmon
        tasks_from: uninstall
    - include_role:
        name: splunk
        tasks_from: uninstall
    - include_role:
        name: velociraptor
        tasks_from: uninstall
