---
- hosts: DC01
  gather_facts: false
  tasks:
    - name: 
      debug: var=hostvars['DC01'].ansible_ssh_host

    #- name: 
    #  debug: var={{ hostvars['DC01']['ansible_eth0']['ipv4']['address'] }}

    #- name: 
    #  debug: var={{ hostvars[groups['domain_controllers'][0]]['ansible_eth0']['ipv4']['address'] }}
